apiVersion: v1
kind: Service
metadata:
  name: gitlabservice
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "http"
      nodePort: 30080
    - protocol: TCP
      port: 443
      targetPort: 443
      name: "https"
      nodePort: 30443
    - protocol: TCP
      port: 22
      targetPort: 22
      name: "ssh"
      nodePort: 30022
